title: Bloom LOG - purelledhand
email: purelledhand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://purelledhand.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Purelledhand # add your name
author-pic: face.jpg
about-author: 의미만 있다면

# Contact links
email: purelledhand@gmail.com  # Add your Email address
github: purelledhand # Add your Github handle
facebook: purelledhand # Add your Facebook handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: purelledhand # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
